services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: web
    command: start --filter=./**/web -- --production
    restart: unless-stopped
    environment:
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
